CODEOWNERS

Adding @uetchy as a code owner

Add @uetchy as CodeOwner

---

prh.yml
style-guide.md

https://github.com/gatsbyjs/gatsby-ja/pull/25#discussion_r366699110 対応
Style Guideに追加。
intro, introduction -> はじめに

Add rules about introduction in styleguide

---

CODEOWNERS

chore: add imbsky as CODEOWNER

---

.github/workflows/label-when-approved.yml
.github/workflows/label-when-created.yml
.github/workflows/lint.yml

I have made some tweaks to `.github/workflows/lint.yml`, but the basic behavior is the same.

Add two label-related workflows

---

README.md

Adding @imbsky as maintainer list in README

docs: add imbsky to maintainers in README

---

docs/tutorial/using-multiple-themes-together.md

tutorial/using-multiple-themes-together を翻訳しました。
レビューお願いします。
原文ページ
https://www.gatsbyjs.org/tutorial/using-multiple-themes-together/

translate tutorial/using-multiple-themes-together

---

docs/docs/gatsby-cli.md

part of #1 
ドキュメントへのリンクは翻訳された状態のものを採用するのかよく分からなかったので、とりあえず残してあります。

translate gatsby-cli

---

docs/docs/recipes/deploying-your-site.md

Translated [docs/recipies/deploying-your-site.md](https://www.gatsbyjs.org/docs/recipes/deploying-your-site/) page into Japanese.
Any comments or suggestions are welcome :)

Translate docs/recipies/deploying-your-site.md

---

docs/docs/glossary.md

docs: translate glossary

---

prh.yml

Slugを`prh.hml`に追加しました。
https://github.com/gatsbyjs/gatsby-ja/pull/85
https://github.com/gatsbyjs/gatsby-ja/pull/126
Ref: #1

chore: add slug to prh.yml

---

prh.yml

`ウェブページ` を `prh.yml` に追加しました。
#128
Ref: #1

Add "web page" to prh.yml

---

docs/docs/gatsby-image.md

[docs/gatsby-image](https://www.gatsbyjs.org/docs/gatsby-image/) を翻訳しました。
レビューよろしくお願いいたします。
Ref: #1

Translate docs/gatsby-image

---

docs/docs/add-a-service-worker.md

`docs/add-a-service-worker.md` の翻訳を修正しました。
`サービスワーカー API` => `Service Worker API`
#147 
Ref: #1

Fix docs/add-a-service-worker.md

---

docs/docs/deploying-to-heroku.md

`docs/deploying-to-heroku` を翻訳しました。
レビューよろしくお願いします:bow:
Ref: #1

Translate docs/deploying-to-heroku

---

docs/docs/basic-hardware-software-requirements.md

`docs/basic-hardware-software-requirements.md`の翻訳PRです。
Ref: #1

feat(docs): translate `basic-hardware-software-requirements`

---

docs/docs/best-practices-for-orgs.md

`docs/best-practices-for-orgs.md` の翻訳PRです。
Ref: #1

feat(docs): translate docs/best-practices-for-orgs

---

.yarnclean

```
λ yarn autoclean --force
yarn autoclean v1.22.0
[1/1] Cleaning modules...
info Removed 1208 files
info Saved 25.49 MB.
✨  Done in 0.85s.
```

Add .yarnclean

---

docs/docs/adding-analytics.md

translate Docs/adding analytics
Ref: #1

translate Docs/adding analytics

---

docs/docs/mdx/getting-started.md

`docs/mdx/getting-started` を翻訳しました。よろしくお願いします。
Ref: #1

translate docs/mdx/getting-started

---

docs/docs/adding-forms.md

`Transrate docs/adding-forms` を翻訳しました。
Ref: #1

Translate docs/adding-forms

---

docs/contributing/stub-list.md

`contributing/stub-list` を翻訳しました。
心配な箇所にコメントを残すので確認していただきたいです。
Ref: #1

Transrate contributing/stub-list

---

.github/labeler.yml
.github/workflows/labeler.yml

This PR adds an action that adds a label when the PR is opened.

Add labeler

---

docs/docs/themes/converting-a-starter.md

https://www.gatsbyjs.org/docs/themes/converting-a-starter/ を翻訳しました。
タイトルは`docs/docs/themes/what-are-gatsby-themes.md` 内のリンクに合わせました。
Ref: #1

Translate docs/docs/themes/converting-a-starter.md

---

docs/docs/recipes/transforming-data.md

transforming-data の追加されたコンテンツを翻訳しました。
Ref: #218

docs: translate additional content for transforming-data

---

docs/docs/security-in-gatsby.md

`docs/security-in-gatsby` を翻訳しましたので、ご確認お願いします 🙇‍♀ 
Ref: #1

docs: translate docs/security-in-gatsby

---

docs/docs/visual-testing-with-storybook.md

visual-testing-with-storybook の追記された部分の翻訳です。
Ref: #218

docs: update translation of visual-testing-with-storybook

---

docs/docs/glamor.md

`docs/glamor` を翻訳しました。
Ref: #1

docs: translate docs/glamor

---

docs/docs/gatsby-on-linux.md

`gatsby-on-linux.md` を翻訳しました。
1箇所 typo を見つけたので本家リポジトリにPRを送っています。
https://github.com/gatsbyjs/gatsby/pull/25160
Ref: #1

docs: Translate docs/gatsby-on-linux

---

docs/contributing/submit-to-starter-library.md

`contributing/submit-to-starter-library` を翻訳しましたのでレビューよろしくお願いします
Ref: #1

docs: translate contributing/submit-to-starter-library

---

docs/docs/recipes/querying-data.md

docs/recipes/querying-data.md を翻訳しました。
Ref: #1

docs: translatedocs/recipes/queryng-data

---

docs/docs/basic-hardware-software-requirements.md
docs/docs/best-practices-for-orgs.md

fix https://github.com/gatsbyjs/gatsby-ja/pull/279#discussion_r465989528
`PullRequest`  --> `Pull Request`
Ref: #1

align the expression of PR

---

docs/docs/building-a-blog.md

Translate building-a-blog.md into Japanese
Ref: #1

docs: translate docs/docs/building-a-blog

---

CODEOWNERS
README.md

I haven't had time to help this lately and have been inactive. And to be honest, I don't want to help the Gatsby team anymore recently. I recommend you look at Nat's posts for details, but that's why I'm leaving the project.

Remove smorimoto from gatsby-ja codeowners list

---

docs/docs/api-reference.md

docs/api-referenceを翻訳しました。
Ref: #1

docs: translate docs/api-reference

---

docs/docs/adding-page-transitions.md

docs/adding-page-transitionsを翻訳した。
Ref: #1

docs: translate docs/adding-page-transitions

---

README.md

Fix(Doc): update .org to .com

---

docs/docs/linking-between-pages.md

Translate Docs/linking between pages

---

docs/docs/images-and-files.md

docs/images-and-files を翻訳しましたのでレビューよろしくお願いします
Ref: #1

docs: translate docs/images and files
