.github/workflows/lint.yml
.huskyrc.js
.textlintrc.js
package.json
prh.yml
yarn.lock

Add [textlint](https://github.com/textlint/textlint) to lint documents.
fixes #2

chore: add textlint

---

.github/workflows/lint.yml

Fetch performance has been improved since `v2.0.0`.
https://github.com/actions/checkout/releases/tag/v2.0.0

chore: bump actions/checkout from v1 to v2

---

.textlintrc.js
package.json
yarn.lock

全角文字と半角文字の間にスペースを入れるための textlint rule を追加しました。
例外として、句読点の周りにはスペース付けなくて良いようになっています。

Add lint rule about spacing

---

.github/workflows/lint.yml

WHY: github-pr-check won't put the result on Check UI since the bot has no permission to post them in a forked repo.

chore(ci): fix textlint CI

---

docs/docs/themes.md

Translate docs/themes

---

docs/docs/using-graphql-playground.md

Translate: docs/using-graphql-playground

---

docs/docs/using-a-plugin-in-your-site.md

Translate docs/using-a-plugin-in-your-site page
Original Page: https://www.gatsbyjs.org/docs/using-a-plugin-in-your-site/
レビューよろしくお願いいたします。

Translate docs/using-a-plugin-in-your-site

---

docs/docs/upgrading-node-js.md

Translate docs/upgrading-node-js

---

docs/docs/v1-release-notes.md

Translated to Japanese and fixed the link to `CHANGELOG.md`.
About the change of the link, the original document is needed to change also, so I made https://github.com/gatsbyjs/gatsby/pull/20644 for it.

Translate docs/v1-release-notes.md

---

docs/docs/recipes/working-with-starters.md

I translated docs/recipes/working-with-starters into Japanese.
Original page: [docs/recipes/working-with-starters](https://www.gatsbyjs.org/docs/recipes/working-with-starters/)
レビューよろしくお願い致します🙇

docs: translate docs/recipes/working-with-starters

---

docs/docs/recipes/transforming-data.md

レビューお願いします🙏
- 原文ページ
https://www.gatsbyjs.org/docs/recipes/transforming-data/

Tanslate transforming data

---

docs/docs/themes/using-multiple-gatsby-themes.md

`docs/themes/using-multiple-gatsby-themes` を翻訳しました。
Origin Page: [Using Multiple Gatsby Themes](https://www.gatsbyjs.org/docs/themes/using-multiple-gatsby-themes/)
レビューお願いいたします 🙏

Translate docs/themes/using-multiple-gatsby-themes

---

docs/docs/sass.md

I translated `docs/sass` into Japanese.
Original page: [docs/sass](https://www.gatsbyjs.org/docs/sass/)

Translate docs/sass

---

docs/docs/static-query.md

`docs/static-query` の翻訳です。
レビューよろしくお願いします 🙇
原文ページ
[Querying Data in Components using StaticQuery](https://www.gatsbyjs.org/docs/static-query/)

Translation docs/static-query into Japanese

---

docs/tutorial/part-one/index.md

`tutorial/part-one` のマークダウン及びテキストを修正しました。
Ref: #1

Fix markdown of tutorial/part-one

---

docs/docs/sourcing-from-hosted-services.md

`docs/sourcing-from-hosted-services` を翻訳しました。よろしくお願いいたします。

Translate docs/sourcing-from-hosted-services

---

docs/docs/running-queries-with-graphiql.md

#1 の対応として、 `docs/running-queries-with-graphiql ` を翻訳しました。
原文ページ：https://www.gatsbyjs.org/docs/running-queries-with-graphiql/

Translation docs/running-queries-with-graphiql into Japanese

---

docs/tutorial/part-five/index.md

- `docs/tutorial/part-five` の翻訳をしました。
- Origin Page: [Source Plugins](https://www.gatsbyjs.org/tutorial/part-five/#build-a-page-with-a-graphql-query)
- マージ済の`part-six` に用語や表現方法を合わせています。
よろしくお願いします。

Translate docs/tutorial/part-five

---

docs/docs/typography-js.md

[docs/typography-js](https://www.gatsbyjs.org/docs/typography-js/) の翻訳をしました。
Ref: #1

Translate docs/typography-js

---

docs/docs/styled-components.md

[`docs/styled-components`](https://www.gatsbyjs.org/docs/styled-components/) を翻訳しました。
レビューよろしくお願いいたします。
Ref: #1

translate docs/styled-components

---

docs/docs/sourcing-from-databases.md

https://www.gatsbyjs.org/docs/sourcing-from-databases/
の翻訳になります。
レビューをよろしくお願いいたしますm(__)m

Translate /docs/sourcing-from-databases/

---

docs/docs/sourcing-from-the-filesystem.md

`docs/sourcing-from-the-filesystem` を翻訳しました。よろしくお願いいたします。
> 最終行の `For further reference,` の良い言い回しが思いつかなかったので `さらに使い方を学びたければ、` という意訳にしました。

Translate docs/sourcing-from-the-filesystem

---

docs/tutorial/theme-tutorials.md

theme-tutorials translated

---

docs/docs/testing-react-components.md

`docs/testing-react-components`の翻訳になります。
お手数ですが、レビューをお願い致します。
原文ページ:
https://www.gatsbyjs.org/docs/testing-react-components/

translated docs/testing-react-components.md

---

docs/docs/api-files.md

`docs/api-files` の翻訳になります！レビューよろしくお願いします！
Ref: #1

translate docs/api-files

---

docs/docs/eslint.md

`docs/eslint` を翻訳しました。
Ref: #1

translate-docs/eslint

---

docs/docs/emotion.md

`docs/emotion` を翻訳しました。
レビューよろしくお願いします。
Ref: #1

Translate docs/emotion

---

docs/docs/testing.md

docs/testing の翻訳を行いました。
確認お願いします。
Ref: #1

add docs for docs/testing

---

docs/docs/recipes/styling-css.md

docs/recipes/styling-css の翻訳です。
レビューお願いいたします 🙇

Translate docs/recipes/styling-css

---

docs/docs/add-page-metadata.md

`docs/add-page-metadata` を翻訳しました。
#103 と文章が一致している箇所があったので、そちらと合わせるようにしています。
MDNへのリンクがあり #103 では英語にリンクしていました。 日本語も存在していたのでこちらのコミットではURLを変えています。
内容も翻訳されているので、日本語版でも問題ないと思いますがどうでしょうか？
レビューよろしくお願いします:bow:
参考: https://github.com/gatsbyjs/gatsby-ja/pull/103/files#diff-d3b8f5cef608d861ead080f61d0b1a2dR163
Ref: #1

Translate docs/add-page-metadata

---

docs/docs/deploying-and-hosting.md

`docs/deploying-and-hosting` を翻訳しました。
レビューよろしくお願いします。
Ref: #1

Translate docs/deploying-and-hosting

---

docs/docs/babel.md

`docs/babel` を翻訳しました。レビューよろしくお願いします。
Ref: #1

translate docs/babel

---

docs/docs/working-with-images.md

[docs/working-with-images](https://www.gatsbyjs.org/docs/working-with-images/)ページを翻訳しました。
内容のレビューをお願いいたします。
- L5「複数デバイス上でパフォーマンス調整のベストプラクティスを利用するには、各画像に複数のサイズと解像度を用意する必要があります。」はあまり上手い翻訳ではないと思っていますが（特に前半）、ちょうどいい表現が見つかりませんでした。サジェストいただけると幸いです。
- 「参考リンク」のタイトルについては、リンク先のドキュメントがまだ翻訳されていないことや平易な表現であることから翻訳していません。
Ref: #1

Translate `docs/working-with-images`

---

package.json

翻訳PRではありません。
`lint:full`コマンドの対象ファイルのglob引数の設定にミスがあるので修正するPRです。
glob形式で引数を渡す場合はクオートで囲う必要があります。これはtextlintのドキュメントにも記載されています。
https://github.com/textlint/textlint#cli
> When running texlint, you can target files to lint using the glob patterns. Make sure that you enclose any glob parameter you pass in quotes.
Ref: #1

fix: lint script glob pattern

---

docs/docs/localization-i18n.md

`docs/localization-i18n`を翻訳しました。
お手数ですが、内容の確認をよろしくお願いします。
Ref: #1

translate docs/localization-i18n

---

docs/docs/bulma.md

`docs/bulma` を翻訳しました！
よろしくお願いします:bow:
Ref: #1

Translate docs/bulma

---

docs/docs/add-a-manifest-file.md

https://www.gatsbyjs.org/docs/add-a-manifest-file/ の日本語翻訳対応しました。
レビューのほどよろしくお願いします！
Ref: #1

Translate docs/add a manifest file

---

docs/docs/deploying-to-firebase.md

`docs/deploying-to-firebase` を翻訳しました。
レビューよろしくお願いします。
Ref: #1

Translate docs/deploying-to-firebase

---

docs/docs/add-offline-support-with-a-service-worker.md

`docs/add-offline-support-with-a-service` を翻訳しました。
レビューよろしくお願いします:bow:
Ref: #1

Translate docs/add-offline-support-with-a-service-worker

---

docs/docs/webpack-and-ssr.md

`docs/webpack-and-ssr`の翻訳になります。
レビューのほど、よろしくお願い致します。
Ref: #1

feat: translate docs/webpack-and-ssr

---

docs/docs/working-with-images-in-markdown.md

` /docs/working-with-images-in-markdown` の翻訳
none
Ref: #1

translate /docs/working-with-images-in-markdown

---

docs/docs/deploying-to-zeit-now.md

`docs/deploying-to-zeit-now` を翻訳しました。
レビューよろしくお願いします。
関連資料にあるプロジェクト例のリンク先が変更されていたので反映しています。
Ref: #1

Tranlate docs/deploying-to-zeit-now

---

docs/docs/mdx/markdown-syntax.md

Translate Docs/mdx/markdown-syntax
- コードブロック内のMarkdownに書かれているタイトルやコンテンツについて、構文解説のわかりやすさを重視し日本語訳を行いました。
- 「Frontmatter」を和訳するかどうか悩みましたが、GraphQLクエリで`frontmatter`と書かなければならないため、コードの一部と考えて英単語のままとさせてもらいました。
Ref: #1

translate Docs/mdx/markdown syntax

---

docs/docs/creating-global-styles.md

https://www.gatsbyjs.org/docs/creating-global-styles/ の翻訳です
1. 原文にはないリンクを追加しました。詳細はPR内コメントをご確認ください https://github.com/gatsbyjs/gatsby-ja/pull/174#pullrequestreview-358477386
Ref: #1

translate docs/creating-global-styles

---

docs/docs/post-css.md

https://www.gatsbyjs.org/docs/post-css/ の翻訳です
N/A
Ref: #1

translate docs/post-css

---

docs/docs/adding-an-rss-feed.md

https://github.com/gatsbyjs/gatsby-ja/issues/1#issuecomment-578457599 で宣言したとおり、表題のドキュメントを翻訳しました。
Ref: #1

Translate docs/adding-an-rss-feed

---

docs/docs/recipes/sourcing-data.md

docs/recipes/sourcing-data を翻訳しました。
レビューよろしくお願いいたします！
Ref: #1

Translate docs/recipes/sourcing-data

---

docs/docs/sourcing-from-graphcms.md

https://www.gatsbyjs.org/docs/sourcing-from-graphcms/ の翻訳
`Getting content on the page` と `Summary` が表現が難しく少々自信がないです。
Ref: #1

translate docs/sourcing-from-graphcms

---

docs/docs/actions.md

`docs/docs/actions` を翻訳しました。よろしくお願いします。
* `Actions` をそのまま `Actions` とするか迷ったのですが、Vuexのドキュメントではアクションと和訳されていたのでそちらに習って `アクション` としました。
Ref: #1

Translate docs/docs/actions

---

docs/docs/adding-search.md

`docs/adding-search.md`を翻訳しました。
よろしくお願いいたします:bow:
- `search`という単語を文脈に合わせて「検索"機能"」と訳している箇所が何箇所かあります。
- 例: ページタイトル「検索機能の追加」
- `your site`や`your website`といった文言を「あなたのサイト」とするか、単に「サイト」とするか迷いましたが、他のページの翻訳に合わせて「あなたのサイト」と訳すようにしました。
- その他、訳が不安な箇所はコメントいたします。
Ref: #1

docs: translate docs/adding-search.md

---

docs/docs/adding-comments.md

https://www.gatsbyjs.org/docs/adding-comments/ の日本語翻訳対応しました。
遅くなってごめんなさい！
Ref: #1

translate docs/adding-comments

---

docs/docs/adding-markdown-pages.md

Translate Docs/adding markdown pages
Ref: #1

Translate Docs/adding markdown pages

---

docs/docs/custom-html.md

```docs/custom-html.md``` を翻訳しました。
お手数おかけしますが、ご確認よろしくお願いいたします。
34行目「〜を持つ div を必要とします。」ですが、「〜を持つ div が必要です。」としたかった所 linter の接続詞の連続チェックに引っ掛かり、良い言い換えが思い付かずくどい言い回しとなってしまいました。もし宜しければ、恐縮ですがフォローいただければと思います。
Ref: #1

Translate docs/docs/custom-html.md

---

docs/docs/api-files-gatsby-ssr.md

`docs/api-files-gatsby-ssr` を翻訳しましたので、ご確認お願いします 💪 
Ref: #1

docs: translate docs/api-files-gatsby-ssr

---

docs/docs/api-files-gatsby-browser.md

`docs/api-files-gatsby-browser.md`を翻訳しました。
ご確認よろしくお願いいたします:bow:
Ref: #1

docs: translate docs/api-files-gatsby-browser

---

docs/docs/mdx/customizing-components.md

docs/docs/mdx/customizing-components.md の翻訳です。
レビューお願いしますm(_ _)m
翻訳前のドキュメントでは，1パラグラフを複数行に分ける書き方がなされていましたが，訳の方は1パラグラフ1行で書いています。
Ref: #1

Translate Docs/mdx/customizing-components

---

docs/docs/api-files-gatsby-node.md

`docs/api-files-gatsby` を翻訳しました。レビューよろしくお願いします。
Ref: #1

Translate api-files-gatsby-node.md

---

docs/docs/adding-page-transitions-with-plugin-transition-link.md

https://www.gatsbyjs.org/docs/adding-page-transitions-with-plugin-transition-link/ の日本語翻訳対応しました。
遅くなってしまって申し訳ありませんが、レビューのほどよろしくお願いします。
Ref: #1

docs:translate docs/adding-page-transitions-with-plugin-transition-link

---

docs/docs/debugging.md

`docs/debuggind`を翻訳しました。
Ref: #1

docs: translate docs/debugging

---

docs/docs/themes/theme-composition.md

`docs/themes/theme-composition`を翻訳しました。
Ref: #1

docs: translate docs/themes/theme-composition

---

docs/docs/headless-cms.md

docs: translate docs/headless-cms

---

.github/workflows/lint.yml

Github Actionsのlint.ymlで利用されている `add-path` コマンドが利用できなくなったことで
失敗してしまっていたので修正しました。
通知
https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
修正時の参考サイト
https://dev.classmethod.jp/articles/replace-deprecated-method-on-actions/
Ref: #335

fix lint.yml for disable add-path command
